PIENSAWEB/PIENSAWEB/Controllers/CMSController.cs
using PIENSAWEB.Models;
using System.Linq.Dynamic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using System.IO;
using PIENSAWEB.Clases;
using System.Drawing;
using System.Text;
using Microsoft.AspNet.Identity;

namespace PIENSAWEB.Controllers
{
    [Authorize]
    public class CMSController : Controller
    {
        private piensaEntities db = new piensaEntities();

        // GET: CMS
        public ActionResult Noticias()
        {
            return View();
        }

        public ActionResult index()
        {
            return View();
        }
        public ActionResult Paginas()
        {
            return View();
        }

        public ActionResult imagenes()
        {
            return View();
        }
        public ActionResult Eventos()
        {
            return View();
        }

        public ActionResult Menus()
        {
           
            return View();
        }

        public ActionResult CreateFotos()
        {
            return PartialView();
        }
        public ActionResult CreateNoticias()
        {
            return PartialView();
        }
        public ActionResult CreateEventos()
        {
            return PartialView();
        }
        public ActionResult CreatePaginas()
        {
            return PartialView();
        }
        public ActionResult CreateDocumentos()
        {
            return PartialView();
        }
        public ActionResult Createdoc()
        {
            return PartialView();
        }

        public ActionResult Documentos()
        {
            return View();
        }

        public ActionResult CreateMenu()
        {
           
            return PartialView();
        }

        [HttpPost]
        public ActionResult upphoto(HttpPostedFileBase photo)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {

                    
                    Archivos p = new Archivos();
                    p.FechaHoraCreacion = DateTime.Now;
                    p.Nombre = photo.FileName;
                    p.IsFoto = true;
                    p.UsuarioCreacion = HttpContext.User.Identity.GetUserId();
                    db.Archivos.Add(p);
                    db.SaveChanges();
                    db.Sp_Audit_Table_User(User.Identity.GetUserId(), "photo");


                    var fileName = Path.GetFileName(photo.FileName);
                    var path = Path.Combine(Server.MapPath("~/img/uploads"), fileName);
                    photo.SaveAs(path);

                    dbContextTransaction.Commit();
                    return Json(new { Message = "S" });
                }
                catch (Exception e)
                {
                    dbContextTransaction.Rollback();
                    return Json(new { Message = "Error" });
                }
            }
           

        }

        [HttpPost]
        public ActionResult EliminarPhoto(int id)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    Archivos p = db.Archivos.Where(w => w.IdArchivo == id).FirstOrDefault();
                    db.Archivos.Remove(p);
                    db.SaveChanges();
                    db.Sp_Audit_Table_User(User.Identity.GetUserId(), "photo");
                    dbContextTransaction.Commit();
                    return Json(new { Message = "S" });

                }
                catch (Exception e)
                {
                    dbContextTransaction.Rollback();
                    return Json(new { Message = "Error" });
                }
            }

        }


        [HttpPost]
        public ActionResult updoc(HttpPostedFileBase doc)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {


                    Archivos p = new Archivos();
                    p.FechaHoraCreacion = DateTime.Now;
                    p.Nombre = doc.FileName;
                    p.IsFoto = false;
                    p.UsuarioCreacion = HttpContext.User.Identity.GetUserId();
                    db.Archivos.Add(p);
                    
                    db.SaveChanges();
                    db.Sp_Audit_Table_User(User.Identity.GetUserId(), "photo");

                    var fileName = Path.GetFileName(doc.FileName);
                    var path = Path.Combine(Server.MapPath("~/doc/uploads"), fileName);
                    doc.SaveAs(path);

                    dbContextTransaction.Commit();
                    return Json(new { Message = "S" });
                }
                catch (Exception e)
                {
                    dbContextTransaction.Rollback();
                    return Json(new { Message = "Error" });
                }
            }


        }

        [HttpPost]
        public ActionResult EliminarDoc(int id)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    Archivos p = db.Archivos.Where(w => w.IdArchivo == id).FirstOrDefault();
                    db.Archivos.Remove(p);
                    db.SaveChanges();
                    db.Sp_Audit_Table_User(User.Identity.GetUserId(), "photo");
                    dbContextTransaction.Commit();
                    return Json(new { Message = "S" });

                }
                catch (Exception e)
                {
                    dbContextTransaction.Rollback();
                    return Json(new { Message = "Error" });
                }
            }

        }

        [HttpPost,ValidateInput(false)]
        public ActionResult agregarnoticia(Post p)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    //p.Contenido = HttpUtility.HtmlEncode(p.Contenido);
                    p.reganulado = false;
                    p.FechaHora = DateTime.Now;
                    p.UsuarioCreacion = HttpContext.User.Identity.GetUserId();
                    db.Post.Add(p);
                    db.SaveChanges();
                    db.Sp_Audit_Table_User(User.Identity.GetUserId(), "post");
                    dbContextTransaction.Commit();

                    return Json(new
                    {
                        message = "exito",

                    });
                }
                catch (Exception er)
                {

                    dbContextTransaction.Rollback();
                    return Json(new
                    {
                        message = "error",
                        error = er.Message
                    });
                }


            }
        }


        [HttpPost, ValidateInput(false)]
        public ActionResult Editarnoticia(Post p)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    p.FechaHora = db.Post.Where(w => w.Idpost == p.Idpost).Select(s => s.FechaHora).FirstOrDefault();
                    p.reganulado = false;
                    db.Entry(p).State = EntityState.Modified;
                    db.SaveChanges();
                    db.Sp_Audit_Table_User(User.Identity.GetUserId(), "post");
                    dbContextTransaction.Commit();
                    return Json(new { Message = "S" });

                }
                catch (Exception e)
                {
                    dbContextTransaction.Rollback();
                    return Json(new { Message = "Error" });
                }
            }

        }


        [HttpPost]
        public ActionResult EliminarNoticia(int id)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    Post r = db.Post.Where(w => w.Idpost == id).FirstOrDefault();
                    r.reganulado = true;
                    db.Entry(r).State = EntityState.Modified;
                    db.SaveChanges();
                    db.Sp_Audit_Table_User(User.Identity.GetUserId(), "post");
                    dbContextTransaction.Commit();
                    return Json(new { Message = "S" });

                }
                catch (Exception e)
                {
                    dbContextTransaction.Rollback();
                    return Json(new { Message = "Error" });
                }
            }

        }


        
        [HttpPost,ValidateInput(false)]
        public ActionResult agregarevento(Post p)
        {
            using (var dbContextTransaction = db.Database.BeginTransaction())
            {
                try
                {
                    //p.Contenido = HttpUtility.HtmlEncode(p.Contenido);
                    p.reganulado = false;
                    p.FechaHora = DateTime.Now;
                    p.UsuarioCreacion = HttpContext.User.Identity.GetUserId();
                    db.Post.Add(p);
                    db.SaveChanges();
                    db.Sp_Audit_Table_User(User.Identity.GetUserId(), "post");
                    dbContextTransaction.Commit();
                    return Json(new
                    {
                        message = "exito",

                    });
                }
                catch (Exception er)
                {

                    dbContextTransaction.Rollback();
                    return Json(new
                    {
                        message = "error",
                        error = er.Message
                    });
                }


            }
        }


        [HttpPost, ValidateInput(false)]
        public ActionResult Editarevento(Post p)
        {

PIENSAWEB/PIENSAWEB/Controllers/EventosController.cs
using PIENSAWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PIENSAWEB.Controllers
{
    public class EventosController : Controller
    {
        private piensaEntities db = new piensaEntities();
        // GET: Eventos

        public ActionResult side()
        {

            //var noti = db.Post.Where(w => w.reganulado == false && w.tipo == 2).OrderByDescending(o => o.Idpost).ToList();
            var noti = db.Post.Where(w => w.reganulado == false && w.tipo == 2).OrderByDescending(o => o.Idpost).ToList();
            return PartialView(noti);
        }

        public ActionResult publicacion(string id)
        {
            int idn = Convert.ToInt32(id);
            var noti = db.Post.Where(w => w.reganulado == false && w.tipo == 2 && w.Idpost == idn).ToList();

            return View(noti);
        }
    }
}

PIENSAWEB/PIENSAWEB/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;


using PIENSAWEB.Models;

namespace PIENSAWEB.Controllers
{
    public class MenusController : Controller
    {
        private piensaEntities db = new piensaEntities();

        // GET: Menus
        [Authorize]
        public ActionResult Index()
        {
            var menu = db.Menu.Include(m => m.Menu2).Include(m => m.Pagina).Include(m => m.Users);
            return View(menu.ToList());
        }
        [Authorize]
        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }
        [Authorize]
        // GET: Menus/Create
        public ActionResult Create()
        {
            ViewBag.MenuPadre = new SelectList(db.Menu, "IdMenu", "Menu1");
            ViewBag.IdPagina = new SelectList(db.Pagina, "idPagina", "Vista");
            ViewBag.UsuarioCreacion = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Menus/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "IdMenu,Menu1,MenuPadre,Icono,Orden,IdPagina,Habilitar,VisibleCMS")] Menu menu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    menu.UsuarioCreacion = HttpContext.User.Identity.GetUserId();
                    menu.FechaCreacion = DateTime.Now;

                    db.Menu.Add(menu);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.MenuPadre = new SelectList(db.Menu, "IdMenu", "Menu1", menu.MenuPadre);
                ViewBag.IdPagina = new SelectList(db.Pagina, "idPagina", "Vista", menu.IdPagina);
                ViewBag.UsuarioCreacion = new SelectList(db.Users, "Id", "Email", menu.UsuarioCreacion);
                return View(menu);
            }
            catch(Exception er)
            {
                ViewBag.MenuPadre = new SelectList(db.Menu, "IdMenu", "Menu1", menu.MenuPadre);
                ViewBag.IdPagina = new SelectList(db.Pagina, "idPagina", "Vista", menu.IdPagina);
                ViewBag.UsuarioCreacion = new SelectList(db.Users, "Id", "Email", menu.UsuarioCreacion);
                return View(menu);

            }
        }
        [Authorize]
        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            ViewBag.MenuPadre = new SelectList(db.Menu, "IdMenu", "Menu1", menu.MenuPadre);
            ViewBag.IdPagina = new SelectList(db.Pagina, "idPagina", "Vista", menu.IdPagina);
            ViewBag.UsuarioCreacion = new SelectList(db.Users, "Id", "Email", menu.UsuarioCreacion);
            return View(menu);
        }

        // POST: Menus/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "IdMenu,Menu1,MenuPadre,Icono,Orden,FechaCreacion,FechaAnulacion,FechaModificacion,UsuarioCreacion,IdPagina,Habilitar,VisibleCMS")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MenuPadre = new SelectList(db.Menu, "IdMenu", "Menu1", menu.MenuPadre);
            ViewBag.IdPagina = new SelectList(db.Pagina, "idPagina", "Vista", menu.IdPagina);
            ViewBag.UsuarioCreacion = new SelectList(db.Users, "Id", "Email", menu.UsuarioCreacion);
            return View(menu);
        }

        // GET: Menus/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menu.Find(id);
            db.Menu.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

       
    }
}

PIENSAWEB/PIENSAWEB/Controllers/PaginaController.cs
using PIENSAWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PIENSAWEB.Controllers
{
    
    public class PaginaController : Controller
    {
        // GET: Error
        private piensaEntities db = new piensaEntities();

        [HttpGet]      
        public ActionResult publicacion(string name)
        {
       
            var pag = db.Pagina.Where(w => w.FechaEliminacion == null && w.Nombre==name && w.VisibleCMS== true).ToList();

            return View(pag);



        }
    }
}

PIENSAWEB/PIENSAWEB/Views/CMS/CreateDocumentos.cshtml
<div class="modal fade right" id="modaldoc" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-animation="false">
    <div class="modal-dialog modal-full-height modal-sm" role="document">
        <!--Content-->
        <div class="modal-content">

            <!--Header-->
            <div class="modal-header blue darken-4  white-text">
                <button type="button" class="close waves-effect waves-light" data-dismiss="modal" aria-label="Close" data-animation="false" data-tooltip="tooltip" data.placement="right" title="Cerrar esta ventana">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="title"><i class="fa fa-pied-piper font-weight-bold" aria-hidden="true"></i> {{gestion}}Documentos</h4>
            </div>
            <!--Body-->
            <div class="modal-body mb-0">

                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-12">
                            <form name="myForm">
                                <fieldset>
                           
                                    Archivo PDF: <input ngf-select="" class="" ng-model="picFile" name="file" ngf-accept="'.pdf'" required="" type="file" ngf-max-size="3MB">
                                    <i ng-show="myForm.file.$error.required">*requerido</i>
                                    <br>
                                  
                                    <img ngf-src="picFile" class="thumb">
                                    <span class="progress" ng-show="picFile.progress >= 0">
                                        <div style="width:{{picFile.progress}}%" ng-bind="picFile.progress + '%'" class="ng-binding"></div>
                                    </span>
                                    <span ng-show="picFile.result">Archivo subido</span>
                                </fieldset>
                                <br>
                               
                            </form>

                        </div>
                    </div>


                    <p class="red-text">{{messageCant}}</p>
                    <div class="form-group font-weight-bold text-center">
                        <div class="text-center">
                            <input type="submit" value="Guardar" class="btn btn-sm blue darken-4" ng-click="guardar()" ng-disabled="!myForm.$valid" />
                        </div>
                        <p class="red-text">{{message}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PIENSAWEB/PIENSAWEB/Views/CMS/Eventos.cshtml
@{
    Layout = "~/Views/Shared/_Layout_A.cshtml";
    ViewBag.Title = "CMS - Eventos PIENSA";
}


<ng-controller ng-controller="CmsNoticiaController" ng-clock>
    <div class="card card-block rounded smooth-scroll">

        <h4 class="h4-responsive indigo-text font-weight-bold">Eventos del sitio </h4>        <hr />


        <div class="table-responsive ">
            <table class="table table-hover  table-bordered table-striped" id="table1">
                <thead class="blue darken-4  white-text">
                    <tr>
                        <th>
                            id
                        </th>

                        <th>
                            Titulo
                        </th>
                        <th>
                            Contenido
                        </th>
                        <th>
                            Fecha/Hora Publicación
                        </th>
                        <th>
                            Fecha/Hora Inicio
                        </th>
                        <th>
                            Fecha/Hora Fin
                        </th>


                    </tr>
                </thead>

                <tbody ng-click="get()"></tbody>

            </table>

        </div>

        <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
            <a class="btn-floating btn-large blue darken-4 ">
                <i class="fa fa-cogs"></i>
            </a>

            <ul>
                <li><a class="btn-floating green" data-an   tion="false" ng-click="nuevo()" data-tooltip=tooltip data-placement="left" title="Agregar una evento al sistema "><i class="fa fa-plus"></i></a></li>
                <li><a class="btn-floating yellow" data-animation="false" ng-click="editar()" data-tooltip=tooltip data-placement="left" title="Editar una evento del sistema"><i class="fa fa-pencil"></i></a></li>
                <li><a class="btn-floating red" data-animation="false" ng-click="eliminar()" data-tooltip=tooltip data-placement="left" title="Eliminar una evento del sistema"><i class="fa fa-trash-o"></i></a></li>

            </ul>
        </div>
        @Html.Action("ModalDelete", "Home", new { v = true })
        @Html.Action("CreateEventos", "CMS")
    </div>

</ng-controller>
  

      
    



        <script>
            app.controller('CmsNoticiaController', ['$scope', '$http', "$window", 'textAngularManager', function wysiwygeditor($scope, $http, $window, textAngularManager) {
                $scope.fechainicio = null;
                $scope.fechafin = null;


                $('.datepicker').pickadate({
                    weekdaysShort: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                    showMonthsShort: true
                });
                var table1 = $('#table1').DataTable({
                    select: true,
                    "processing": true,
                    "serverSide": true,
                    "orderMulti": false,
                    "ajax": {
                        "url": "../CMS/searchEventos",
                        "type": "POST",
                        "dataType": "JSON"

                    },
                    "columns": [
                        { "data": "Idpost", "name": "Idpost", "visible": false },
                          { "data": "Titulo", "name": "Titulo" },
                          { "data": "Contenido", "name": "Contenido" },
                        {
                            "data": "FechaHora", "name": "FechaHora", "render": function (data) {
                                var date = new Date(parseInt(data.substr(6)));
                                return date.getDate() + "/" + (date.getMonth()+1) + "/" + date.getFullYear();
                                // return data;
                            }},
                        {
                            "data": "fechainicio", "name": "fechainicio", "render": function (data) {
                                var date = new Date(parseInt(data.substr(6)));
                                return date.getDate() + "/" + (date.getMonth() + 1) + "/" + date.getFullYear();
                               // return data;
                            }
                        },
                        {
                            "data": "fechafin", "name": "fechafin", "render": function (data) {
                                var date = new Date(parseInt(data.substr(6)));
                                return date.getDate() + "/" + (date.getMonth() + 1) + "/" + date.getFullYear();
                            }}

                    ],

                    "language": {
                        "lengthMenu": "Mostrando _MENU_ Entradas por pagina",
                        "zeroRecords": "Lo sentimos, no se encuentran concidencias",
                        "info": "Mostrando Página _PAGE_ de _PAGES_ (Registros Totales _TOTAL_)",
                        "infoEmpty": "No hay entradas Disponibles",
                        "infoFiltered": "(filtrar por _MAX_ total entradas)",
                        "search": "Buscar",
                        "paginate": {
                            "previous": "Anterior",
                            "next": "Siguiente"
                        }, "select": {
                            rows: " "
                        }
                    }

                });

                $('#table1 tbody').on('click', 'tr', function () {
                    var idt = table1.row(this).index();
                    var t = table1.cell(idt, 0).data();
                    $scope.evento = t;
                    var date1 = new Date(parseInt(table1.cell(idt, 4).data().substr(6)));                   
                    $scope.fechainicio = date1;
                    var date2 = new Date(parseInt(table1.cell(idt, 5).data().substr(6)));
                    $scope.fechafin = date2;                
                    $scope.titulo = table1.cell(idt, 1).data();
                    $scope.contenido = table1.cell(idt, 2).data();

          

                  

                    


                });

                $scope.nuevo = function () {

                    if ($scope.evento != 0) {
                        $scope.clear();

                    }
                    $('#modaleventos').modal({
                        show: true
                    })

                }

                $scope.editar = function () {

                    if ($scope.evento != 0) {
                        $scope.edit = true;
                        $('#modaleventos').modal({
                            show: true
                        })

                    }


                }


                $scope.guardar = function () {
                    if ($scope.fechainicio != null) {
                        $scope.date1 = $scope.fechainicio.getDate() + "-" + ($scope.fechainicio.getMonth()+1) + "-" + $scope.fechainicio.getFullYear()
                    }
                    if ($scope.fechainicio != null) {
                        $scope.date2 = $scope.fechafin.getDate() + "-" + ($scope.fechafin.getMonth() + 1) + "-" + $scope.fechafin.getFullYear()
                    }

                    if ($scope.edit == true) {
                        $scope.evento = $scope.evento + 0;
                        $scope.contenido = $scope.contenido + "";
                        $scope.titulo = $scope.titulo + "";
                      

                        if ($scope.evento > 0 && $scope.contenido.length > 4 && $scope.titulo.length > 4 && $scope.fechainicio != null && $scope.fechafin != null) {


                            $http({
                                url: "../CMS/Editarevento",
                                method: "POST",
                                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                                data: $.param({ "Idpost": $scope.evento, "Titulo": $scope.titulo, "Contenido": $scope.contenido, "Tipo": 2, "FechaHoraInicioEvento": $scope.date1, "FechaHoraFinEvento": $scope.date2 })
                            }).then(function (result) {
                                if (result.data.Message == 'S') {
                                    $('#modaleventos').modal('hide');
                                } else {
                                    $scope.message = "Error: En la transaccion"
                                }

                            });
                        }

                    } else {
                     

                        if ($scope.contenido.length > 4 && $scope.titulo.length > 4 && $scope.fechainicio != null && $scope.fechafin != null) {

                            $http({
                                url: "../CMS/agregarevento",
                                method: "POST",
                                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                                data: $.param({ "Titulo": $scope.titulo, "Contenido": $scope.contenido, "Tipo": 2,"FechaHoraInicioEvento": $scope.date1, "FechaHoraFinEvento": $scope.date2  })
                            }).then(function (result) {
                                if (result.data.message == 'exito') {
                                    $('#modaleventos').modal('hide');
                                } else {
                                    $scope.message = "Error: En la transaccion"
                                }

                            });





                        } else {
                            $scope.message = "Error: Son requeridos todos los campos";
                        }
                    }


                };


                $scope.eliminar = function () {
                    if ($scope.evento != 0) {


                        $('#modaldelete').modal({
                            show: true
                        })
                    }
                };

                $scope.delete = function () {
                    $http({
                        url: "../CMS/EliminarNoticia",
                        method: "POST",
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        data: $.param({ "id": $scope.evento })
                    }).then(function (result) {
                        if (result.data.Message == "S") {
                            $('#modaldelete').modal('hide');

                        }

                    });
                }


                $scope.clear = function () {
                    $scope.message = "";
                    $scope.evento = 0;
                    $scope.titulo = "";
                    $scope.contenido = "";
                    $scope.fechainicio = null;
                    $scope.fechafin = null;
                    $scope.titulo = "";
                    $scope.edit = false;
                    $('#table1').DataTable().ajax.reload();
                 
                }

                $scope.clear();

                $('#modaleventos').on('hidden.bs.modal', function (e) {
                    $scope.clear();
                });

                $('#modaldelete').on('hidden.bs.modal', function (e) {
                    $scope.clear();
                });

            }]);
        </script>